.php-unit-test:
  stage: test
  variables:
    COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer"
  cache:
    paths:
      - .composer
  before_script:
    - mkdir -p .composer build/logs
    - composer install --no-interaction
  script:
    - composer test -- --colors=always

php71-unit-test:
  extends: .php-unit-test
  image: iras/php7-composer:1
  before_script:
    - mkdir -p .composer build/logs
    - composer install --no-interaction --ignore-platform-reqs

php72-unit-test:
  extends: .php-unit-test
  image: iras/php7-composer:2
  before_script:
    - mkdir -p .composer build/logs
    - composer install --no-interaction --ignore-platform-reqs

php73-unit-test:
  extends: .php-unit-test
  image: iras/php7-composer:3

php74-unit-test:
  extends: .php-unit-test
  image: iras/php7-composer:4
  variables:
    CI_NAME: "gitalb-ci"
    CI_BUILD_NUMBER: "$CI_JOB_ID"
    CI_BRANCH: "$CI_COMMIT_REF_NAME"
    CI_BUILD_URL: "$CI_JOB_URL"
  script:
    - php -dzend_extension=xdebug.so -dxdebug.mode=coverage vendor/bin/phpunit -c phpunit.xml --coverage-clover=build/coverage.xml --coverage-text --colors=always
  after_script:
    - composer require php-coveralls/php-coveralls:~2.4@stable
    - php vendor/bin/php-coveralls -v -x build/coverage.xml

php80-unit-test:
  extends: .php-unit-test
  image: iras/php8-composer:0
