language: php
dist: trusty
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "7.4" ]; then composer require satooshi/php-coveralls:~0.6@stable; fi;'
  - mkdir -p build/logs

script:
  - composer code-style
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "7.4" ]; then
      composer coverage -- --colors=always;
    else
      composer test -- --colors=always;
    fi;'

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "7.4" ]; then php vendor/bin/coveralls -v -x build/coverage.xml; fi;'
