language: php

sudo: false

matrix:
  include:
    - php: 7.1
      dist: trusty
    - php: 7.0
      dist: trusty
    - php: 5.6
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: hhvm
      dist: trusty
    - php: 5.3
      dist: precise

cache:
  directories:
    - $HOME/.composer/cache

before_script:
 - composer install
